language: perl
perl:
- "5.10"
- "5.22"
addons:
  apt:
    sources:
    - debian-sid
before_install:
- sudo apt-get update
- sudo apt-get install -t precise --no-install-recommends build-essential libssl-dev
- sudo apt-get install -t precise --no-install-recommends python-docutils
- sudo apt-get install -t unstable --no-install-recommends libnss-wrapper libsocket-wrapper
install:
- cpanm Date::Format Date::Parse HTML::Form HTML::HeadParser HTML::TreeBuilder IO::Socket::SSL IPC::Run JSON LWP::UserAgent LWP::Protocol::https Net::HTTPS Net::SSLeay
- cpanm Perl::MinimumVersion
- cpanm Perl::Critic
before_script:
- make -C t/certs/
script:
- make -C doc/
- ls doc/*.rst | xargs -t -n1 -I{} rst2xml --strict {} /dev/null
- private/run-perlcritic
- prove --verbose

# vim:ts=2 sts=2 sw=2 et
