language: perl
perl:
- "5.10"
- "5.24"
addons:
  apt:
    sources:
    - debian-sid
before_install:
- sudo apt-get update
- APT_INSTALL='sudo apt-get install --no-install-recommends'
- $APT_INSTALL -t precise build-essential libssl-dev
- $APT_INSTALL -t precise python-docutils
- $APT_INSTALL -t unstable libnss-wrapper libsocket-wrapper
install:
- cpanm Date::Format Date::Parse HTML::Form HTML::HeadParser HTML::TreeBuilder IO::Socket::SSL IPC::Run JSON LWP::UserAgent LWP::Protocol::https Net::HTTPS Net::SSLeay
- cpanm Perl::MinimumVersion
- cpanm Perl::Critic
before_script:
- make -C t/certs/
script:
- make -C doc/
- private/check-rst
- private/run-perlcritic
- prove --verbose

# vim:ts=2 sts=2 sw=2 et
